### PR TITLE
pixelgl has been ported to GLFW 3.3.

### PR DESCRIPTION
**Pull request by zergon321**
Examples from the **pixel-examples** repository work good. Soon I will work on the gamepad support,

### CODE REVIEW

**Comment by tracer8086** [comment]
I have added a gamepad support. Actually, the old code didn't work correctly, because if you work with gamepad you have to use `GetGamepadState` instead of `GetButtons` or `GetAxes`, otherwise the gamepad won't be properly mapped and its inputs will be interpreted incorrectly. For those who want to know more about mappings: [GLFW Input Guide](https://www.glfw.org/docs/latest/input_guide.html#gamepad_mapping). Also you may check [the full set of GLFW mappings](https://github.com/glfw/glfw/blob/master/src/mappings.h).

**Comment by steelx** [comment]
When is this going to get merged ? @faiface  if you update pixel you get glfw errors

**Comment by Chillance** [comment]
Yeah, so what is going on here @faiface and @tracer8086 ? @tracer8086 seems to have a fork with using glwf 3.3, so should I move over to that?

**Comment by jrcichra** [comment]
I'm also interested in glfw 3.3. Can we get some eyes on this PR @faiface ?

**Comment by icholy** [comment]
I've done some basic testing of this fork against my lib and I didn't run into any issues. https://github.com/icholy/slippy

**Comment by icholy** [comment]
@zergon321 would probably be better to split these changes into 2 PRs.

1. Update to GLFW 3.3
2. Make breaking changes.

**Comment by zergon321** [comment]
@icholy Yeah, that's right, but what I really needed personally is proper gamepad support which is impossible without moving to **GLFW 3.3**. But updating the repo to **GLFW 3.3** is more global, so I named the PR after it.

**Comment by icholy** [comment]
@zergon321 I understand, I just think these changes should be split up across two separate PRs so they can considered in isolation.

**Comment by zergon321** [comment]
@icholy Ok, I've reverted two commits fixing the gamepad API. I hope this PR will get merged because the gamepad API just doesn't work correctly in its present state, and, moreover, it's incomplete.

**Comment by delp** [comment]
@zergon321 I'm going to do #219 to get into the swing of things...Hope to do it today. Then I'll take a look at this

**Comment by delp** [comment]
Awesome, maybe I can get this out this weekend! If so I like your idea that this be tagged "x.x.x-alpha"

**Comment by delp** [comment]
OK lets go!

**Pull request merged**
