### PR TITLE
pixelgl: export UpdateInput

### LINKED ISSUE #78: Provide API for polling window events without redrawing the screen
My friends and I have been playing around with integrating Pixel in a game, and we would like to be able to poll for window events without having to redraw the screen.

In our use case, we don't control when when rendering happens as we integrate Pixel into an already existing game engine. We'd still like to poll window events to forward actions triggered by mouse and keyboard events to the game engine.

Locally, we've been using the following patch. If there is a better way to do it, I'd definitely be happy to discuss alternatives. Also, if the design decision is to keep the Pixel API minimal, I understand if you'd wish not to apply this change and expose more of the API. If so, we can continue to use this patch locally.

```diff
diff --git a/pixelgl/input.go b/pixelgl/input.go
index ff98805..2bbb3a4 100644
--- a/pixelgl/input.go
+++ b/pixelgl/input.go
@@ -372,7 +372,7 @@ func (w *Window) initInput() {
        })
 }
 
-func (w *Window) updateInput() {
+func (w *Window) UpdateInput() {
        mainthread.Call(func() {
                glfw.PollEvents()
        })
diff --git a/pixelgl/window.go b/pixelgl/window.go
index 26d96f7..3716574 100644
--- a/pixelgl/window.go
+++ b/pixelgl/window.go
@@ -192,7 +192,7 @@ func (w *Window) Update() {
                w.end()
        })
 
-       w.updateInput()
+       w.UpdateInput()
 }
 
 // SetClosed sets the closed flag of the Window.
@@ -244,6 +244,7 @@ func (w *Window) SetPos(pos pixel.Vec) {
                w.window.SetPos(left, top)
        })
 }
+
 // Bounds returns the current bounds of the Window.
 func (w *Window) Bounds() pixel.Rect {
        return w.bounds
```

Cheers,
/u & i

### PR DESCRIPTION
**Pull request by mewmew**
Fixes #78.

### CODE REVIEW

**Comment by mewmew** [comment]
Travis CI succeeded on Go tip, and failed on Go 1.8 and Go 1.7.4. However, the failures are not related to this change.

From Go 1.7.4 error log: "could not create session key: disk quota exceeded"

From Go 1.8 error log:  "Failed to connect to github.com port 443"

**Comment by faiface** [comment]
Thanks! Sorry for responding so late, I've been rather busy with other things.

The patch is fine, except the documentation could be more descriptive. Right now, it's misleading because it suggests that you *need* to call this method in order to get input at all, which is not true. The doc should clarify this.

Then I'll merge.

**Comment by mewmew** [comment]
> Thanks! Sorry for responding so late, I've been rather busy with other things.

No worries :) Hope you had a good winter holidays!

> The patch is fine, except the documentation could be more descriptive. Right now, it's misleading because it suggests that you need to call this method in order to get input at all, which is not true. The doc should clarify this.

Sure. The latest commit included a clarification of this.

> Then I'll merge.

PTAL. If the docs need further improvement, simply let me know.

Cheers,
/u

**Comment by faiface** [comment]
Ok, the doc's fine now.

Yeah, I'm doing pretty good, got addicted to a philosophy history podcast in my leisure time. Hope you have a good time as well! And with Pixel too!

**Pull request merged**
