### PR TITLE
add sudoku community example

### PR DESCRIPTION
**Pull request by jwangsadinata**
This commit adds a simple sudoku community example that demonstrates the
use of text batching and imdraw drawing capabilities.

### CODE REVIEW

**Comment by thegtproject** [comment]
Very cool! Thank you so much for this. faiface is busy with finals this week, but, he should get around to adding this soon enough!

**Comment by faiface** [comment]
Hey, this is a cool example! How hard would it be to add random generation of the field?

**Comment by jwangsadinata** [comment]
Hey @faiface, thanks for the feedback. On my personal repo, I used someone else's package for the random generation, which I can probably include it here too if you think that's better. My first idea on this is to just create a community example that is standalone and pretty easy to follow, so I cut out a few things on this. Anyway, let me know and I can gladly update it.

**Comment by faiface** [comment]
Alright, I'll merge this, but if you feel like adding the random generation in the future, feel free to PR that ;) Thanks a lot for this cool example!

**Pull request merged**
