### PR TITLE
Fix vertex race

### PR DESCRIPTION
**Pull request by bcvery1**
Turns out this was happening when calling `NewGLTriangles`, the last two function calls in this function are
 - `gt.SetLen` which concurrently sets the length of the underlining `VertexSlice`
 - `gt.Update` which reads the length of the underlining `VertexSlice`

This resulted in a timing issue (during investigation, I stopped the data race with `fmt.Println` debug lines!).  I've made it so `gt.SetLen` synchronously sets the length, and added a test for this; adding the test has meant introducing `xvfb` to travis, but works for TilePix

Resolves faiface/glhf#5

### CODE REVIEW

**Comment by faiface** [comment]
Oh, right! Thanks, @bcvery1, merging immediately!

**Comment by faiface** [comment]
Oh, I forgot to merge :D. I see you added some commits. Is it ready for merging?

**Comment by bcvery1** [comment]
Yeah, my bad - the tests weren't passing on Travis until just now.  Last two changes were just the testing env.

Ready for merge :+1:

**Comment by faiface** [comment]
Great!

**Pull request merged**
