### PR TITLE
add a guide for making scenes

### PR DESCRIPTION
**Pull request by jwangsadinata**
This commit introduces a way to work with scenes by introducing a scene
type and a function to move between it.

### CODE REVIEW

**Comment by jwangsadinata** [comment]
I feel this is a simple and straightforward way of demonstrating how to work with scenes, that might be beneficial to anyone interested in using this library. I think this is the best place to put it, but let me know if it is not. I am all ears to inputs and suggestions.

**Comment by jwangsadinata** [comment]
Ah I see, I was not aware of the wiki thing. That's also very true that there are many ways of accomplishing this, and this is not a default way to do it. Regular example sounds good to me. To clarify, which directory exactly should the regular example be? under the `examples/community`?

**Comment by faiface** [comment]
Yes, `examples/community` would be the right place right now.

**Comment by faiface** [comment]
Thanks. Should've merged long ago. Merging now.

**Pull request merged**
