### PR TITLE
why 2 loops and assign twice? one is enough

### PR DESCRIPTION
**Pull request by Immueggpain**

### CODE REVIEW

**Comment by Immueggpain** [comment]
Actually, we can do some optimizations here. Right now we just recalculate everything....

**Comment by bcvery1** [comment]
@Immueggpain considering that `s.tri` will always be of length 6* (see [line 27](https://github.com/faiface/pixel/blob/master/sprite.go#L27)), you could remove the `for` loop all together, if you were trying to improve efficiency via in-lining...

_*happy to be corrected if this is an incorrect assumption_

**Comment by Immueggpain** [comment]
@bcvery1 at the cost of significantly more code...
I was thinking about line 78. Say if ony the mask is changed, we can simply reassign colors of vertices, without recalculating transformations for positions.
But after a second thought... both optimizations (loop unrolling) would make the code less concise. I think we might just leave it at its current state.

**Comment by faiface** [comment]
Heh, not really sure why it was two loops... So thanks, I'm merging this :)

**Pull request merged**
