### PR TITLE
Added SetCursorMode()

### PR DESCRIPTION
**Pull request by theGeekPirate**
http://www.glfw.org/docs/3.1/input.html#cursor_mode

Mainly implemented to allow window-based mouse locking, but should (and does) support all other cursor modes as well.

### CODE REVIEW

**Comment by theGeekPirate** [comment]
As a side-note, the cursor can still move away from the camera view (while still contained inside the application), so you have to implement some sort of bounds-checking on top to be contained the way we would normally see in games.

Not sure if this is the intended functionality or if there's an issue in the other libraries somewhere, but all the graphics stuff is frankly above my head, which is why I'm using this nice library in the first place =b

**Comment by faiface** [comment]
Hi! Sorry I haven't responded earlier, I'm pretty busy with school right now. Anyway, thanks for the PR, although I'm not convinced this is very useful (feel free to prove me wrong). We already have the ability to hide the cursor, so what this adds is the ability to disable it. I'm not sure where this would be useful.

**Comment by theGeekPirate** [comment]
This doesn't only hide the cursor, it also prevents it from leaving the window.

**Comment by faiface** [comment]
Yeah, I understand that, but it's mostly useful in FPS games, which this library is not aiming at. But now that I think of it, it's actually also useful in 2D shooter games, too, so okay, it can be done.

But, the API needs to be different. We already have a function for hiding the cursor. I'd propose simply adding another one to disable the cursor, like this:

```go
func (w *Window) SetCursorDisabled(disabled bool) { ... }
```

A disabled cursor would always override a hidden cursor.

**Comment by theGeekPirate** [comment]
Should work the way you requested now.

**Comment by theGeekPirate** [comment]
> A disabled cursor would always override a hidden cursor.

Perhaps I misunderstood—did you want to create a window property for disabled, and prevent SetCursorVisible(false/true) from overriding SetCursorDisabled()?

**Comment by faiface** [comment]
The way you did it is not bad actually, but yeah, a `Window.CursorDisabled` method would be fine too. And if that's gonna happen, then it's probably worth it to just do it the way I meant it initially, which is something like this:

```
visible & disabled = disabled
visible & !disabled = visible
!visible & disabled = disabled
!visible & !disabled = hidden
```

**Comment by faiface** [comment]
Ok, cool, just one more change request. As you surely see, `SetCursorVisible` and `SetCursorDisabled` are really similar, so please, extract this similarity to a separate unexported function and I'll merge.

**Comment by theGeekPirate** [comment]
Should be it 👍

**Comment by faiface** [comment]
Ok, I noticed one more problem, if the cursor is disabled, calling `SetCursorVisible` won't have any effect on the flag, which it should. After that change, you can extract even more code into the unexported function. I'm sorry, I just have a high quality standard, in case you're tired of this, I can do it myself in like 2 days, but finishing it now will be appreciated.

**Comment by theGeekPirate** [comment]
> Ok, I noticed one more problem, if the cursor is disabled, calling SetCursorVisible won't have any effect on the flag, which it should.

I did that on purpose, since it wouldn't be visible even if set alongside the cursor being disabled, which means calling CursorVisible() would return the incorrect value otherwise.

I guess it depends on whether or not you want CursorVisible() to display whether or not the cursor is _actually_ visible or not at the current moment, or simply to see what that property is set to, regardless of what the user sees.

**Comment by faiface** [comment]
I understand that, but I like the idea of just setting flags better. The overall outcome should depend on the flags as I drafted in one of the previous messages.

Like, yeah, the API is not ideal, but I don't want to make it backward incompatible, nor inconsistent.

**Comment by theGeekPirate** [comment]
Yar, if I continue to use the library, I'll probably just fork a version for myself which only has SetMouseMode(), as it seems to currently add more confusion for the user to understand at the moment...

> "Why doesn't SetCursorVisible(true) actually make the cursor visible, and why doesn't CursorVisible() tell me if the cursor is actually visible or not?"

...but I of course understand your backwards compatibility issue.

I'll probably leave the rest of this up to you in that case, sorry =c

**Comment by faiface** [comment]
Ok, no problem. I'll try to resolve this in a few days. Perhaps I'll end up with a solution similar to your original one, but I need more time to think about it.

**Comment by PlainSight** [comment]
I don't know how helpful this is regarding implementing backwards compatible cursor mode functionality (sorry if this is off topic) but I implemented a disable cursor feature in a fork which additionally locks the cursor within the window (as well as hiding it): https://github.com/faiface/pixel/compare/master...PlainSight:master 

I could then render it manually to get a performant cursor locked to the application window:
`cursor.Draw(win, pixel.IM.Moved(win.MousePosition()))`

Though this is doing more than just disabling the cursor it could be nice to have native library support for a locked cursor mode.

**Comment by faiface** [comment]
Closing this now.

**Pull request closed without merging**
