### PR TITLE
Break geometry.go & geometry_test.go into multiple smaller files

### LINKED ISSUE #286: Move Geometry into its own package
While looking into #277, i noticed the `geometry.go` & `geometry_test.go` files have 1100+ & 1400+ lines each. Maybe this could be refactored out into its own package, and broken up into smaller files (`rectangle.go`, `vec.go`, etc.) to make it easier to maintain down the road not to mention reduce the large amount of functions and types currently exported by the main `github.com/faiface/pixel` package.

### PR DESCRIPTION
**Pull request by cebarks**
Closes #286.

### CODE REVIEW

**Comment by faiface** [comment]
While Pixel is not technically 1.0, it's being used as it is and breaking changes should only be introduced in cases where they bring substantial benefits to the users of the library. Which I don't think is the case for this change. I appreciate the effort, but I don't think this is a good idea.

**Comment by cebarks** [comment]
That's fair @faiface, as I did it the more i thought maybe it wasn't the best idea. What do you think about still breaking out `geometry.go` into multiple files?

**Comment by faiface** [comment]
Yes, breaking it up sounds good. It would make things easier to navigate.

**Comment by dusk125** [comment]
@cebarks can you check to make sure that any new changes tests in geometry are merged into your broken out files please before I merge this in?

**Comment by cebarks** [comment]
> @cebarks can you check to make sure that any new changes tests in geometry are merged into your broken out files please before I merge this in?

Should be good to go now @dusk125 :)

**Review by dusk125 — APPROVED** [review]
Thanks!

**Pull request merged**
