### PR TITLE
Added DisableCursor

### PR DESCRIPTION
**Pull request by jared-nishikawa**
Resolves https://github.com/faiface/pixel/issues/213

### CODE REVIEW

**Comment by aerth** [comment]
Tested, works great.
```
if g.win.JustPressed(g.settings.keymap[KeyToggleMouse]) {
			if g.settings.mousedisabled {
				g.win.DisableCursor()
			} else {
				g.win.SetCursorVisible(false)
			}
			g.settings.mousedisabled = !g.settings.mousedisabled
		}
```

I was (at first) confused how to re-enable the cursor.  (`SetCursorVisible(true)`)

Maybe consider renaming to `SetCursorDisabled()`

This is the best mouse setting, thank you!

**Comment by jared-nishikawa** [comment]
Thanks for the feedback!  Name is changed.

**Comment by delp** [comment]
Triaging PRs... let's call this one 2nd in line after https://github.com/faiface/pixel/pull/219 is finished.

**Comment by jared-nishikawa** [comment]
@delp Hey I just got caught up on the news about the transition in leadership.  Congrats!  Happy to talk about this PR if/when you need to.

**Comment by delp** [comment]
@jared-nishikawa Thanks! I just merged in https://github.com/faiface/pixel/pull/219 this weekend. Giving it a bit to get feedback on wheher or not I did everything satisfactorily (changelog, version/tag, testing/writing down how i tested etc) then I'll try to get this one in next before moving on to the big GLFW update

**Comment by delp** [comment]
Testing with the examples, tests, etc.

**Comment by delp** [comment]
@jared-nishikawa Looks good to me.

**Pull request merged**
