### PR TITLE
Fix circle intersect

### LINKED ISSUE #161: Imperfect Circle-Rect intersection
https://github.com/faiface/pixel/blob/8563c2849321d1983afee63d52d8bc6287968dd0/geometry.go#L486

This function produces a non-optimal solution for diagonal vectors.

The function should provide the *shortest* vector to ensure there is no intersection, however when this vector should be diagonal, the actual result is a horizontal or vertical vector.

### PR DESCRIPTION
**Pull request by bcvery1**
Resolves #161 

@faiface Please do critic my logic on this

### CODE REVIEW

**Comment by faiface** [comment]
Thanks! I believe this passes all the previous tests and some new as well, right? If so, I have no problem merging this.

**Comment by bcvery1** [comment]
@faiface Yes, all tests passing

**Comment by faiface** [comment]
Cool! Then I'm merging

**Comment by faiface** [comment]
Well, we've got some errors.

**Comment by bcvery1** [comment]
@faiface what errors?  All tests are passing, I'm assuming there is a logical error?

**Comment by faiface** [comment]
Sorry I wasn't being specific. Some tests didn't pass: https://travis-ci.org/faiface/pixel

**Comment by faiface** [comment]
Alright, tests passed, it's the build that failed for Go tip. Will you look into it? If not, I'll look into it later.

**Comment by bcvery1** [comment]
It seems stalled on `travis_setup_go` for tip; on the other versions this took 0.11s and 3.92s.  Not sure I know enough about travis to make any intelligent guess, but the failure is occurring before running tests on the code

**Comment by faiface** [comment]
Okay, I force reran the build/tests on Travis and now it all passed. Sorry for bothering you, could've tried sooner.

**Pull request merged**
