### PR TITLE
Infinite scrolling background demo

### PR DESCRIPTION
**Pull request by svera**

### CODE REVIEW

**Comment by faiface** [comment]
Very nice! Will definitely merge. Two things that would be nice, but if you don't have time, no problem:

1. Make it framerate independent, like at the end of this tutorial: https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix

2. Make the window larger.

Let me know if you'll implement these changes!

**Comment by svera** [comment]
@faiface sure, sounds fair, I'll let you know when ready.

**Comment by svera** [comment]
@faiface changes done.

**Comment by faiface** [comment]
Cool! Thanks for a nice example!

**Pull request merged**
