### PR TITLE
Add related repository TilePix to README

### PR DESCRIPTION
**Pull request by bcvery1**
I have started a package to unify working with Tiled and working with Pixel.

It is under active development, but I hope will be very useful to others even in its current state (all basics covered).

I would be very happy if you'd consider allowing a link to my new repo from the Pixel ReadMe.  If you'd prefer not to, or not to at this time, not a problem.

### CODE REVIEW

**Comment by Noofbiz** [comment]
I wrote a tmx parser for go a while back if you want to use that :P
https://github.com/Noofbiz/tmx

**Comment by faiface** [comment]
@bcvery1 Wow, the package is actually very well crafted, documented and its features are awesome! I'm quite impressed!

I'm gonna accept this PR.

Btw, @bcamp1, you're a very good Pixel contributor. Keep doing whatever you feel like, but if you'd ever wanna tackle [this issue](https://github.com/faiface/pixel/issues/46) let me know. That would be highly appreciated! (All your other contributions are highly appreciated as well.)

**Comment by faiface** [comment]
Btw, @bcvery1, I have one suggestion for your package. I'd suggest renaming all those `GetX()` methods to just `X()`. That would be more idiomatic Go.

One other thing is that your license is MIT, but your badge shows GPL-3.0.

**Comment by bcvery1** [comment]
@faiface it has been a pleasure contributing to Pixel, and I intend to continue to do so.  Maybe I will look at that issue when I get a moment (currently trying to install a few more hours in the day, but I think there are dependencies conflicts).

Thank you again for merging this in, it is much appreciated.

Thank you for your suggestion! I'll keep it in mind

**Comment by elliotmr** [comment]
Isn't GPL 3.0 a big problem here? I hope that everybody understands that since there is only static linking in Go, by including the TilePix library in their game they must have an GPL3.0 compatible license and they must release their source code. From the last line of the license:

> The GNU General Public License does not permit incorporating your program
> into proprietary programs.  If your program is a subroutine library, you
> may consider it more useful to permit linking proprietary applications with
> the library.  If this is what you want to do, use the GNU Lesser General
> Public License instead of this License.  But first, please read
> <https://www.gnu.org/licenses/why-not-lgpl.html>.

**Comment by bcvery1** [comment]
@elliotmr if that is the case, and it would seem to be, I will get it updated to something more appropriate asap.  Thank you for making me aware!

**Comment by faiface** [comment]
@bcvery1 Yeah, that's right! MIT or something would be better.

**Comment by bcvery1** [comment]
Thank you both - I've changed this to MIT (if the badge is showing GPL still, it's a caching issue)

**Pull request merged**
