### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by alistanis**
Performs terribly (lots of glitches due to excessive allocations) but works. Meant as a prototype - this was a fast implementation without a ton of thought

### CODE REVIEW

**Comment by faiface** [comment]
Good for the first pass! Needs:
1. move into separate package ".../audio/playback"
2. set buffer size in time.Duration
3. don't export any other methods than Update and Play
4. the two streamer cases (n==len(samples) and 0<n<len(samples)) can be merged
5. optimize
6. document

**Comment by alistanis** [comment]
A little confused by what you mean on 2. Do you want me to set the buffer size by the expected time a single buffer should hold like I did in other sample code?

**Comment by alistanis** [comment]
@faiface Pushed some changes.

I addressed:
 1. Moved to separate package, "playback"
 2. No extra exports
 3. Merged read cases
 4. Added documentation

That was all I could do in the minimal time I had here.

**Comment by alistanis** [comment]
I also removed the example for now, if I have time to fix it I'll add it back

**Pull request merged**
