### PR TITLE
add community example: amidakuji

### PR DESCRIPTION
**Pull request by NaniteFactory**
Hi. This adds a community example called "Amida Kuji" I made.
(Amida Kuji is a method of lottery very popular in East Asia.)

repo: https://github.com/NaniteFactory/amidakuji

Here is how it looks:

Some of its effects are from other (community) examples including `bouncing` and `starfield`.

Please accept this PR if you like it. xD

### CODE REVIEW

**Comment by faiface** [comment]
Hey, this is very cool! Thanks a lot for submitting this example. I assume everything is right with this, so I'll just merge and then test it out :P

**Comment by faiface** [comment]
Okay, so it actually errored on the CI. Do you mind figuring out what went wrong and fixing it? Thanks a lot.

**Comment by mewmew** [comment]
From https://travis-ci.org/faiface/pixel/jobs/423637172:

```
# pkg-config --cflags  -- pango
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
pkg-config: exit status 1
```

**Comment by mewmew** [comment]
@NaniteFactory Looks good to me, at least at a first glance. Now, it's up to merge it and see if Travis-CI is also happy :)

**Pull request merged**
